title: David Zumaquero
email: zumaquerodavid@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
Personal web page where you can know me better.
baseurl: https://davidzuma.github.io
url: https://davidzuma.github.io/David-Zumaquero/
github_username:  davidzuma

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
