title: David Zumaquero
email: zumaquerodavid@gmail.com
description: Personal web page where you can know me better.
baseurl: https://davidzuma.github.io
url: https://davidzuma.github.io/David-Zumaquero/
github_username:  davidzuma

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

